ServerName 127.0.0.1
ServerTokens Prod
ServerSignature Off

<Directory /var/www/html/public>
    Options FollowSymLinks
    AllowOverride All
    Require all granted
    DirectoryIndex index.php
</Directory>
