CREATE TABLE IF NOT EXISTS users (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    firstname VARCHAR(100) NOT NULL,
    lastname VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL,
    username VARCHAR(100) NOT NULL,
    password VARCHAR(255) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY users_email_unique (email),
    UNIQUE KEY users_username_unique (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS password VARCHAR(255) NULL AFTER username;

-- No login credentials are seeded. Create an administrator with a
-- password generated by PHP's password_hash() before signing in.

CREATE TABLE IF NOT EXISTS products (
    id INT NOT NULL AUTO_INCREMENT,
    product_name VARCHAR(100) NOT NULL,
    description TEXT,
    price DECIMAL(10,2) NOT NULL,
    quantity INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO products (product_name, description, price, quantity)
SELECT 'Wireless Mechanical Keyboard', 'Compact hot-swappable keyboard with Bluetooth and USB-C connectivity.', 3499.00, 18
WHERE NOT EXISTS (SELECT 1 FROM products WHERE product_name = 'Wireless Mechanical Keyboard');

INSERT INTO products (product_name, description, price, quantity)
SELECT 'Ergonomic Office Chair', 'Adjustable mesh chair with lumbar support and a breathable backrest.', 6895.50, 9
WHERE NOT EXISTS (SELECT 1 FROM products WHERE product_name = 'Ergonomic Office Chair');

INSERT INTO products (product_name, description, price, quantity)
SELECT '27-inch QHD Monitor', 'IPS display with 1440p resolution, 100 Hz refresh rate, and adjustable stand.', 12490.00, 7
WHERE NOT EXISTS (SELECT 1 FROM products WHERE product_name = '27-inch QHD Monitor');

INSERT INTO products (product_name, description, price, quantity)
SELECT 'USB-C Docking Station', 'Nine-port desktop dock with HDMI, Ethernet, card reader, and power delivery.', 2799.75, 24
WHERE NOT EXISTS (SELECT 1 FROM products WHERE product_name = 'USB-C Docking Station');
